name: format

on: push

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Install dependencies
        run: |
          cd bin/fetch
          poetry config virtualenvs.create false
          poetry install --no-root -n
      - run: autopep8 --aggressive --exit-code --recursive --diff ./bin/fetch/
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Install dependencies
        run: |
          cd bin/fetch
          poetry config virtualenvs.create false
          poetry install --no-root -n
      - run: black --check ./bin/fetch/
  vint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludvighz/vint-action@v1
        with:
          path: ./matt/.config/nvim/
